### ISSUE TITLE
Add evermore colormap

### ISSUE THREAD

**Issue by maximumcats** [JBorrow/swiftascmaps#1]
Taylor Swift has announced that [she is releasing](https://twitter.com/taylorswift13/status/1337020334122397697) a new album [evermore](https://twitter.com/taylorswift13/status/1337021903417044992). Could you please add a colormap to go along with the new record?

**Comment by JBorrow** [comment]
This has been addressed in v1.1.0. We will not be making a major revision at this time as evermore is expected to be of a similar artistic style to folklore, which coincided with our v1.0.0 release (please see commit https://github.com/JBorrow/swiftascmaps/commit/bbb0faca9117a6c6d8d5c5391f779fa599c850e5).

Thank you for your interest in `swiftascmaps`.
